[package]

name = "cgmath"
version = "0.8.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Brian Heylin",
        "Colin Sherratt",
        "Dzmitry Malyshau",
        "Erick Tryzelaar",
        "Luqman Aden",
        "Maik Klein",
        "Mikko Perttunen",
        "Pierre Krieger",
        "Tomasz Stachowiak"
]
license = "Apache-2.0"
description = "A linear algebra and mathematics library for computer graphics."

documentation = "http://bjz.github.io/cgmath"
homepage = "https://github.com/bjz/cgmath"
repository = "https://github.com/bjz/cgmath"
readme = "README.md"

keywords = ["gamedev", "math", "matrix", "vector", "quaternion"]

[lib]
name = "cgmath"

[features]
unstable = []

[dependencies.rustc-serialize]
rustc_serialize = "0.3"

[dependencies]
num = "0.1"
rand = "0.3"

[dev-dependencies]
glium = "0.13.5"
